spring:
  application:
   name: FinanceTracker

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financetracker
    username:  postgres
    password:  postgres
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  jwt:
    secret: daf66e01593f61a15b857cf433eee03a005812b31234e149036bbb8dee755dbb
    expiration: 86400000